package config

var KeycloakPublicKey = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyHlx19nfp/hKgiTbKVniLN9xscwXMOGJAWhTOiRbmw53sMBJqCZpdHjxwEayg/Z2AGkbsIMOyApl4yr/bfRzGcbzdXw8uLLF/z7xltdImmeXO9kU0tKrZFk5okXuK+TK86OUzdHXoQn5vOxVHGeLmfjQPtJK9FZhoMg2v5NX4bTtQAPF/ZxPwma/1fEn7SYfQb9oE6ZKYBdhwXcYHwELqpCoPRgcLE0E3Vj3t/I7+3t3Ctj+EsU/srC3AcLgksZd4ZkCyKtFJU9Le0CTz+gcOzRx9ojinLM0vTKaeR1nSMvLpF4ZiDAWkbzrT/FHGn4T8Hd03/r3xXpPUwvEVGGSuQIDAQAB
-----END PUBLIC KEY-----`